/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PostfixOperator;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Postfix Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PostfixOperatorImpl extends ExpressionImpl implements PostfixOperator
{
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostfixOperatorImpl()
	{
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass()
	{
		return MyDslPackage.Literals.POSTFIX_OPERATOR;
	}

} //PostfixOperatorImpl
