/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PrefixOperator;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Prefix Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrefixOperatorImpl extends ExpressionImpl implements PrefixOperator
{
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrefixOperatorImpl()
	{
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass()
	{
		return MyDslPackage.Literals.PREFIX_OPERATOR;
	}

} //PrefixOperatorImpl
