/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.StringManipulationStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>String Manipulation Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StringManipulationStatementImpl extends StatementImpl implements StringManipulationStatement
{
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringManipulationStatementImpl()
	{
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass()
	{
		return MyDslPackage.Literals.STRING_MANIPULATION_STATEMENT;
	}

} //StringManipulationStatementImpl
