/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Import</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Import#getImportedElement <em>Imported Element</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Import#getImportedElements <em>Imported Elements</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Import#getImportURI <em>Import URI</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Import#getElement <em>Element</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Import#getAlias <em>Alias</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getImport()
 * @model
 * @generated
 */
public interface Import extends Statement
{
	/**
	 * Returns the value of the '<em><b>Imported Element</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Import}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Imported Element</em>' containment reference list.
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getImport_ImportedElement()
	 * @model containment="true"
	 * @generated
	 */
	EList<Import> getImportedElement();

	/**
	 * Returns the value of the '<em><b>Imported Elements</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Import}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Imported Elements</em>' containment reference list.
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getImport_ImportedElements()
	 * @model containment="true"
	 * @generated
	 */
	EList<Import> getImportedElements();

	/**
	 * Returns the value of the '<em><b>Import URI</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Import URI</em>' attribute.
	 * @see #setImportURI(String)
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getImport_ImportURI()
	 * @model
	 * @generated
	 */
	String getImportURI();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Import#getImportURI <em>Import URI</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Import URI</em>' attribute.
	 * @see #getImportURI()
	 * @generated
	 */
	void setImportURI(String value);

	/**
	 * Returns the value of the '<em><b>Element</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Element</em>' attribute.
	 * @see #setElement(String)
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getImport_Element()
	 * @model
	 * @generated
	 */
	String getElement();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Import#getElement <em>Element</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Element</em>' attribute.
	 * @see #getElement()
	 * @generated
	 */
	void setElement(String value);

	/**
	 * Returns the value of the '<em><b>Alias</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Alias</em>' attribute.
	 * @see #setAlias(String)
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getImport_Alias()
	 * @model
	 * @generated
	 */
	String getAlias();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Import#getAlias <em>Alias</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Alias</em>' attribute.
	 * @see #getAlias()
	 * @generated
	 */
	void setAlias(String value);

} // Import
