/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Join Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.JoinFunctionCall#getStr <em>Str</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.JoinFunctionCall#getDelimiter <em>Delimiter</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getJoinFunctionCall()
 * @model
 * @generated
 */
public interface JoinFunctionCall extends StringManipulationFunctionCall
{
	/**
	 * Returns the value of the '<em><b>Str</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Expression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Str</em>' containment reference list.
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getJoinFunctionCall_Str()
	 * @model containment="true"
	 * @generated
	 */
	EList<Expression> getStr();

	/**
	 * Returns the value of the '<em><b>Delimiter</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Delimiter</em>' containment reference.
	 * @see #setDelimiter(StringLiteral)
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getJoinFunctionCall_Delimiter()
	 * @model containment="true"
	 * @generated
	 */
	StringLiteral getDelimiter();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.JoinFunctionCall#getDelimiter <em>Delimiter</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Delimiter</em>' containment reference.
	 * @see #getDelimiter()
	 * @generated
	 */
	void setDelimiter(StringLiteral value);

} // JoinFunctionCall
