/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Slice Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SliceFunctionCall#getStr <em>Str</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SliceFunctionCall#getStart <em>Start</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SliceFunctionCall#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSliceFunctionCall()
 * @model
 * @generated
 */
public interface SliceFunctionCall extends StringManipulationFunctionCall
{
	/**
	 * Returns the value of the '<em><b>Str</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Str</em>' containment reference.
	 * @see #setStr(Expression)
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSliceFunctionCall_Str()
	 * @model containment="true"
	 * @generated
	 */
	Expression getStr();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SliceFunctionCall#getStr <em>Str</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Str</em>' containment reference.
	 * @see #getStr()
	 * @generated
	 */
	void setStr(Expression value);

	/**
	 * Returns the value of the '<em><b>Start</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Start</em>' attribute.
	 * @see #setStart(int)
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSliceFunctionCall_Start()
	 * @model
	 * @generated
	 */
	int getStart();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SliceFunctionCall#getStart <em>Start</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Start</em>' attribute.
	 * @see #getStart()
	 * @generated
	 */
	void setStart(int value);

	/**
	 * Returns the value of the '<em><b>End</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>End</em>' attribute.
	 * @see #setEnd(int)
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSliceFunctionCall_End()
	 * @model
	 * @generated
	 */
	int getEnd();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SliceFunctionCall#getEnd <em>End</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>End</em>' attribute.
	 * @see #getEnd()
	 * @generated
	 */
	void setEnd(int value);

} // SliceFunctionCall
