/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Manipulation Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStringManipulationFunctionCall()
 * @model
 * @generated
 */
public interface StringManipulationFunctionCall extends StringManipulationStatement
{
} // StringManipulationFunctionCall
