/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Manipulation Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStringManipulationStatement()
 * @model
 * @generated
 */
public interface StringManipulationStatement extends Statement
{
} // StringManipulationStatement
