/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Try Catch Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TryCatchStatement#getTryBlock <em>Try Block</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TryCatchStatement#getException <em>Exception</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TryCatchStatement#getCatchBlock <em>Catch Block</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTryCatchStatement()
 * @model
 * @generated
 */
public interface TryCatchStatement extends Statement
{
	/**
	 * Returns the value of the '<em><b>Try Block</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Try Block</em>' containment reference.
	 * @see #setTryBlock(Block)
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTryCatchStatement_TryBlock()
	 * @model containment="true"
	 * @generated
	 */
	Block getTryBlock();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TryCatchStatement#getTryBlock <em>Try Block</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Try Block</em>' containment reference.
	 * @see #getTryBlock()
	 * @generated
	 */
	void setTryBlock(Block value);

	/**
	 * Returns the value of the '<em><b>Exception</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Exception</em>' attribute.
	 * @see #setException(String)
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTryCatchStatement_Exception()
	 * @model
	 * @generated
	 */
	String getException();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TryCatchStatement#getException <em>Exception</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Exception</em>' attribute.
	 * @see #getException()
	 * @generated
	 */
	void setException(String value);

	/**
	 * Returns the value of the '<em><b>Catch Block</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Catch Block</em>' containment reference.
	 * @see #setCatchBlock(Block)
	 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTryCatchStatement_CatchBlock()
	 * @model containment="true"
	 * @generated
	 */
	Block getCatchBlock();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TryCatchStatement#getCatchBlock <em>Catch Block</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Catch Block</em>' containment reference.
	 * @see #getCatchBlock()
	 * @generated
	 */
	void setCatchBlock(Block value);

} // TryCatchStatement
